### ISSUE TITLE
Cannot build ride as server if ffa-anti-grief is enabled

### ISSUE THREAD

**Issue by Lastorder-DC** [CorySanin/openrct2-ffa-plugin-suite#1]
"NO PLAYER INDEX" error occurs if player is server itself.

**Comment by CorySanin** [comment]
I only get the error when placing entrances/exits. Or when building track design rides, like mentioned in issue https://github.com/OpenRCT2/OpenRCT2/issues/12762

Do you get these messages when placing track pieces or placing shops/stalls?

**Comment by Lastorder-DC** [comment]
No, only placing entrances/exits. forgot to mention that.

**Comment by CorySanin** [comment]
Then the latest commit should fix the issue 🙂
