### ISSUE TITLE
ip-ban not able to identify users IP

### ISSUE THREAD

**Issue by meowkat** [CorySanin/openrct2-ffa-plugin-suite#2]
Hello,
it seems when using ip-ban.js the plugin is not able to identify users IP. Whenever someone joins the server it just shows 
"[username] IP: 3000::" 
in the chat logs. It does not actually show their IP.
When I IP ban someone it bans everyone in the server. presumably because the plugin thinks everyone's ip is a Null value. And as everyone's IP is null, it bans everyone.

chat logs:
{BABYBLUE}{PALEGOLD}Free For All: {WHITE}userName IP: 3000::

Not sure if it matters but I run about 6 servers instances all on different port numbers.

Thanks for the plugins!

**Comment by CorySanin** [comment]
I also run multiple instances and it's not a problem for me. Can you describe your setup? What OS is this on? What version of OpenRCT2 are you using? Are you using LogMeIn Hamachi or some similar software?
