### ISSUE TITLE
cheat-toggle appears unable to set the staff speed

### ISSUE THREAD

**Issue by SoraBytes** [CorySanin/openrct2-ffa-plugin-suite#3]
I was curious if you knew how to toggle the staff speed with the "cheat-toggle.js" I've listed information below on what I have tried, and explanations below the examples on why I did what I did in attempting to figure it out on my own. Any further assistance in figuring out how to actually toggle them to "fast" would be great thank you!

These are examples of some of the ways I have tried but not all of them.
```
setCheatAction(28, 1, 2);
setCheatAction(28, 1, 3);
setCheatAction(28, 3);
setCheatAction(28, 2);
setCheatAction(28, 1, 0xFF);
setCheatAction(28, 3, 0xFF);
setCheatAction(28, 0xFF);
```

I got the [0xFF](https://github.com/OpenRCT2/OpenRCT2/blob/18dec7d5c54ca035f7366ad625a486a506c4c28b/src/openrct2/Cheats.h#L129), and [0-2 and 1-3](https://github.com/OpenRCT2/OpenRCT2/blob/18dec7d5c54ca035f7366ad625a486a506c4c28b/src/openrct2/Cheats.h#L16-L18) based on OpenRCT2 source and not fully understanding what to use originally. I eventually realized it uses a 0 value index for enums due to figuring out that the DisableVandalism cheat appears to be ID 13 which this toggles by default. With that I'm under the impression it is ID 28 for Staff Speed due to the enum of [Cheats.h](https://github.com/OpenRCT2/OpenRCT2/blob/18dec7d5c54ca035f7366ad625a486a506c4c28b/src/openrct2/Cheats.h#L50-L102) source file.

**Comment by CorySanin** [comment]
The trick I use is to log the actions:

```
context.subscribe('action.execute', e => {
    console.log(e);
});
```

Which outputs:

```
{ action: 'cheatset',
  args: 
   { type: 28,
     param1: 255,
     param2: 0,
     flags: -2147483648 },
  player: 1,
  type: 66,
  isClientOnly: false,
  result: 
   { error: 0,
     cost: 0 } }
```

28 is definitely the type. Seems param1 is the speed from 0 to 255. In fact, your last example `setCheatAction(28, 0xFF)` works!

**Comment by SoraBytes** [comment]
Thats super weird it works for you. However for me as soon as I log onto the server and hired staff they moved at normal speeds with a test comparison of having to open the cheat menu and toggled between "fast" and "normal"

I also tested the code snippet you provided for logging by inserting it after [line 14](https://github.com/CorySanin/openrct2-ffa-plugin-suite/blob/master/lib/cheat-toggle.js#L14) and the output is an error due to syntax. I'm not familiar with this language at all so, I cant really judge where I might have gone wrong assuming its not a simple copy/paste to the correct position. The line number for the error in my case is a mismatch by a large margin due to me copying and pasting the [Cheats.h](https://github.com/OpenRCT2/OpenRCT2/blob/18dec7d5c54ca035f7366ad625a486a506c4c28b/src/openrct2/Cheats.h#L50-L102) section as a comment, and giving myself a small reminder for me to start at 0 for each item. Basically my line 79 is the original files line 14.

 ```
Listening for clients on *:11753
Failed to load plug-in script: SyntaxError: parse error (line 79)
```

My modified version:
```
        if (network.mode === 'server') {
            setCheatAction(6); // Chain Lift All Tracks
            setCheatAction(7); // Fast Hill Lift
            setCheatAction(13); // Disable Vandalism
            setCheatAction(17, 5000000); // Set Money (5,000,000 = $500,000 ??? No Idea.)
            setCheatAction(28, 0xFF); // Set Staff Speed (Fast)
            setCheatAction(37); // Open Park (boolean)
            setCheatAction(42); // Own All Land
            setCheatAction(43); // Disable Ride Value Aging
            setCheatAction(44); // Ignore Research Status
            setCheatAction(52); // Remove Park Fence
            context.subscribe('interval.tick', function () {
                if (date.ticksElapsed % 10000 === 0) {
                    setCheatAction(23);
                }
            });
            context.subscribe('action.execute', e => {
                console.log(e);
            });
        }
```

It appears that the cheat's 28, 42, 52 do not work. I'm unsure if cheat 43 is working.

**Comment by CorySanin** [comment]
Oh, that's because that code snippet is for the [typescript source](https://github.com/CorySanin/openrct2-ffa-plugin-suite/blob/master/src/cheat-toggle.ts). Duktape doesn't support arrow functions so tsc removes them for me.

If you want to drop it in without mucking with TS (I don't blame you), it would be:

```
context.subscribe('action.execute', function (e) {
    console.log(e);
});
```

**Comment by SoraBytes** [comment]
Thank you, and you're right it is being set for staff speed and that "0xFF" or "255" works! However after further troubleshooting I determined how it works for a dedicated server.

In the case of a dedicated server, it gets set at boot and a client joins the staff are normal because for whatever reason the variable is applied once globally and its not syncing across the network repeatedly, and hiring new staff afterwards it doesn't apply to them... Which is why I was chasing the wrong fix. If you change the code around to something like below the staff start working appropriately, it takes a bit of time between updates though. Eventually the staff zoom around like crazy. I assume its the same for the "Ten Minute Inspections" which is why I placed it here as well.

```
            context.subscribe('interval.tick', function () {
                if (date.ticksElapsed % 1000 === 0) { // Not sure? It seems quicker compared to below
                    setCheatAction(28, 0xFF); // Set Staff Speed (Fast)
                    setCheatAction(33) // Ten Minute Inspections
                }
                if (date.ticksElapsed % 10000 === 0) {
                    setCheatAction(23); // Set Grass Length
                    setCheatAction(24); // Water Plants
                }
            });
```

I think it might also apply to cheat's 52 (Remove Park Fence), and 42 (Own All Land). As they don't seem to work when initially executed by the server. Just a thought, I haven't tried testing it as I don't know how yet to execute it only as a client joins.

Question:
What would I set the value to, or where can I find out how to determine the value to set so that its roughly every few minutes in-game? So that staff updates are quick, but not constantly being broadcasted?

`                if (date.ticksElapsed % 1000 === 0)`

**Comment by CorySanin** [comment]
I'm not sure what the tickrate is, your on your own there 😉

But I'm not sure your assessment of staff speed is entirely correct. I'm starting up a headless server with `setCheatAction(28, 0xFF)` in my plugin and when I join as a client, all staff are moving at full speed. New staff don't, which is surprising to me. But instead of executing it on an interval, you could subscribe to `action.execute` and only execute the cheat when a new staff member is hired. That's probably how I'd do it.

**Comment by SoraBytes** [comment]
The reason behind my assumption on staff speed being very wrong and confused is because I've got false information from initial testing, and started assuming how it works. You're also trying with a park *with* staff, and I am starting a park *without* staff (blank) and having no knowledge of how this game really operates (my first experience with scripting, I didn't even know it had any!) I was doing a lot of source code digging, testing, and was not getting results atleast from visual perspective when I got in-game, but I fully neglected to try a park that already had staff to verify against which did not help my understanding of it. Thank you for helping me figure it out.

Also subscribing to `action.execute` is way better method than running on a timer, I don't know why I didn't consider it. Thanks to this [comment](https://github.com/CorySanin/openrct2-ffa-plugin-suite/issues/3#issuecomment-1817741949) I've changed the code to the below code, and everything is working! When hiring new staff they're all fast immediately.

```
        if (network.mode === 'server') {
            //setCheatAction(13); // Disable Vandalism
            setCheatAction(17, 5000000); // Set Money (5,000,000 = $500,000 ??? No Idea.)
            setCheatAction(43); // Disable Ride Value Aging
            setCheatAction(44); // Ignore Research Status
            context.subscribe('interval.tick', function () {
                if (date.ticksElapsed % 10000 === 0) {
                    setCheatAction(23); // Set Grass Length
                    setCheatAction(24); // Water Plants
                }
            });
            context.subscribe('action.execute', function (e) {
                if (e.action === "staffhire") {
                    setCheatAction(28, 0xFF); // Set Staff Speed (Fast)
                }
            });
        }

```

Thank you very much for the assistance!
